name: Deploy Tech Radar to Github Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clone build-your-own-radar
        run: git clone https://github.com/thoughtworks/build-your-own-radar.git

      - name: Install dependencies
        working-directory: build-your-own-radar
        run: npm install

      - name: Ensure data directory exists
        run: mkdir -p build-your-own-radar/files

      - name: Copy radar data
        run: cp data/radar.json build-your-own-radar/files/radar.json

      - name: Build radar
        working-directory: build-your-own-radar
        run: npm run build:prod

      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-your-own-radar/dist
